### PR TITLE
Add a footer credit

### PR DESCRIPTION
**Pull request by MattFielding**
This is to add a Code Enigma credit to the footer of the page. As agreed with Hedley in about March '15. Sorry it's taken us so long to get this done, the task kinda got lost in CE's Redmine and was recently unearthed.

### CODE REVIEW

**Comment by MattFielding** [comment]
Hey @hedleysmith o/
Is this something you can merge please?
Cheers,
Matt

**Comment by hedleysmith** [comment]
@MattFielding yep will do that right now! Sorry, this PR was not on my radar. Thanks for the hosting :)

**Comment by MattFielding** [comment]
cheers dude!

**Comment by hedleysmith** [comment]
No worries. Hmmm, looks I can't SSH into the server though, probably need to add my IP to the whitelist. I'll add a ticket for that.

**Comment by hedleysmith** [comment]
@MattFielding OK all deployed

**Pull request merged**
